---
# Variable configuration.
- name: Check os and version
  debug:
    msg: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}"

- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
  - ansible_os_family == 'RedHat'
  - ansible_distribution != 'Fedora'

- name: Include OS-specific variables (Fedora).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Fedora'

- name: Define caddy_version.
  set_fact:
    caddy_version: "{{ __caddy_version }}"
  when: caddy_version is not defined

- name: Define caddy_bin_path.
  set_fact:
    caddy_bin_path: "{{ __caddy_bin_path }}"
  when: caddy_bin_path is not defined

- name: Define caddy_config_path.
  set_fact:
    caddy_config_path: "{{ __caddy_config_path }}"
  when: caddy_config_path is not defined

